DROP_MOVIE_TABLE = '''DROP TABLE IF EXISTS MOVIES'''

DROP_PROJECTIONS_TABLE = '''DROP TABLE IF EXISTS PROJECTIONS'''

DROP_USERS_TABLE = '''DROP TABLE IF EXISTS USERS'''

DROP_RESERVATIONS_TABLE = '''DROP TABLE IF EXISTS RESERVATIONS'''

CREATE_MOVIE_TABLE = '''
    CREATE TABLE IF NOT EXISTS MOVIES(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        NAME TEXT NOT NULL,
        RATING DECIMAL(0, 10) NOT NULL
    )
'''

CREATE_PROJECTIONS_TABLE = '''
    CREATE TABLE IF NOT EXISTS PROJECTIONS(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        MOVIE_ID INTEGER NOT NULL,
        TYPE VARCHAR(3),
        DATE TEXT NOT NULL,
        TIME TEXT NOT NULL,
        FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID)
    )
'''

CREATE_USER_TABLE = '''
    CREATE TABLE IF NOT EXISTS USERS(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME TEXT NOT NULL,
        PASSWORD TEXT NOT NULL,
        IS_ACTIVE INTEGER NOT NULL DEFAULT 0
    )
'''

CREATE_RESERVATION_TABLE = '''
    CREATE TABLE IF NOT EXISTS RESERVATIONS(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USER_ID INTEGER  NOT NULL,
        PROJECTION_ID INTEGER NOT NULL,
        ROW INTEGER NOT NULL,
        COL INTEGER NOT NULL,
        FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
        FOREIGN KEY(PROJECTION_ID) REFERENCES PROJECTIONS(ID)
    )
'''

CREATE_MOVIE = '''INSERT INTO movies (name, rating)
                  VALUES (%s, %s);'''

LIST_MOVIES = '''SELECT * FROM movies'''
